kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  name: os-sample-python
  namespace: test-basivi
  labels:
    app: os-sample-python
spec:
  strategy:
    type: Rolling
    rollingParams:
      updatePeriodSeconds: 1
      intervalSeconds: 1
      timeoutSeconds: 600
      maxUnavailable: 25%
      maxSurge: 25%
    resources: {}
    activeDeadlineSeconds: 21600
  triggers:
    - type: ConfigChange
  replicas: 1
  revisionHistoryLimit: 10
  test: false
  selector:
    app: os-sample-python
    deploymentconfig: os-sample-python
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: os-sample-python
        deploymentconfig: os-sample-python
    spec:
      containers:
        - name: os-sample-python
          image: 'docker.io/basivireddy/os-sample-python:latest'
          ports:
            - containerPort: 8080
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler

